#ENC[AES256_GCM,data:T7iW7FyKgl93hoTo/lVTiJTgMq3I7AIu/ElRn4m4zxCEM5+zFvzi6TeYnQ==,iv:hawfZrCRUuEecdnvLqgMzyjs7MzvSX3icRnfeojr/fY=,tag:Zbwpm+V0l+UA5vRXGaqxyA==,type:comment]
#ENC[AES256_GCM,data:5K2MPNOqnx1tHqRisAoxbMejp7t+h/1VKRtJVLEXNvcgSCWOkRtozHiPcAGtoG/zC7ABUHYWVZ8=,iv:0nuXwvj2/qqpytVHk46ajMk9cV+w/VjrJM+Sz7Rdu0s=,tag:okUFt9Cb2SDmdCfbBoMShQ==,type:comment]
#
#ENC[AES256_GCM,data:yz9Fh3KBH+jxAG8T7IM1zzoUYq9kEh1z4kfJsDeIReODWXe/QwLgUu6MbTqKxqiMFbn/,iv:ER6mf7v/3N4ISoRjwUmsL4E36Y+oYOJQicF1Zr5crvA=,tag:XJ3GYeDVPxQ0QjF2hrcHkg==,type:comment]
#ENC[AES256_GCM,data:TJlEIK5im4Gu8SVf5uWX6FrZ0QD7/WvKWcEjjOvUxbAqo9pd0UYdq1lqlKM51Z3zpEH6k8oxkA==,iv:+4ihTjPsLURdZgsz8+m9FHygTHC0+MLrjvPI2PvH+uA=,tag:13kJeR/6dekDvlrV1gZU+g==,type:comment]
#ENC[AES256_GCM,data:2R2hfAS9/9R8LBUhvM+VtJCApjYWBXX/WBGPdTX5qA3PgCbUeR2bL9bpWVhGj89LucwvJNe4nl3/xU9P,iv:psLg0oIxyZ2NehUS/LHaaaW7nfa3JiiRSenYqA6EDt4=,tag:ZHgP0a7xM+F+SKVG8iZsAw==,type:comment]
#ENC[AES256_GCM,data:x80Kv1sP018NQ2nOe49uLfOCzWPE5ArtckkyjQiIS7ZfhPo6wddFbhZKVUfHUR5rfKfvZCELa4oyFcH6IAQe4e5+pq/PqHTQ+hfcFqUJU9M6TrPSlfJ+,iv:0dHz846TFn2z8GeaxFp/zPLqW9cytRaSCh6YwZqP9sI=,tag:FWNom0/modBdhEz913izYA==,type:comment]
#
#ENC[AES256_GCM,data:uHuXGmW7ZNCittcIAcyzbKir5xSTvk8vLM/OyA==,iv:6xsfG7EUr3o4bUOscavYsbne/5E9Zt8AbXt8DZcQ6/Y=,tag:9ydQYg4cu1p+Yk4qh1Q14A==,type:comment]
#ENC[AES256_GCM,data:Kguc3EYeBeYItHQFWHQKZlG2tH741q0fHTwNOQ==,iv:wJwY/pVnsGeS4Xhid3hl74M3kGiVZaoSzt+xsHgJjVM=,tag:cVEgGsVFFbUk8/pT2NckkA==,type:comment]
#ENC[AES256_GCM,data:p8mkgFY0K+YYrZjb/caISVUQL+n/R7budSFlaFg=,iv:ZF9Aoe/avG4Ya2pUVX9gofT4DfS8dVhxswNBvmP5T3o=,tag:4JzkqiKmkJy2A3oiIwuHJg==,type:comment]
#ENC[AES256_GCM,data:AbFHSiagiyEZQAmkb3dMYif8TxeBVTr08Z6Z/VvKQLWi6Z6+GsEwo00xLV7naHldlm1cns8MJYmTlT6vowhX5cLxWrKq5a6ycsrQgffAln7hog==,iv:9EPtfu0vcJTGaDaBhdHNLqWdJnv/Z0XeBTUqDmKlY/I=,tag:j/GTrlcx1KEiVksoPTXWJA==,type:comment]
#ENC[AES256_GCM,data:FB0iTtFfuhVCZO7bbQ/EuAhPw6OVOMEJDqKJhTW+4hlYrfDhBEVIb8I+MATM,iv:qtecBnF5CrBIzvKQ/B+ATgBw4SEWDCyqDr8FybDCfcM=,tag:6xsCnFIqXyt31LOPb/D6pw==,type:comment]
proxmox_user: ENC[AES256_GCM,data:wVE4qPJsheO4rQ==,iv:M4okpfnCj5+s6fqfNIuqUHfh/YHBxWXS0RkocbjFlqg=,tag:B6Euiu3n76IrGIc+oOshZQ==,type:str]
proxmox_password: ENC[AES256_GCM,data:63T7IADp6Z1dVYTgD5/hITo6xtV+zZ6KJQ==,iv:0hz0it3RrBRIK/reCem6zCPSzTXlqLMZ8nOuG/9fjW0=,tag:lSOjH93qC+Z8awlUc6Xw/g==,type:str]
proxmox_role_name: ENC[AES256_GCM,data:b03ajBs9AzMpShT8wn0=,iv:s2wZipYfPi05qVT8RXHyD5tzsHt+jDvRvgMWbaOhBds=,tag:6az8eF4gJZ18vFgOOJ6TXQ==,type:str]
#ENC[AES256_GCM,data:hRmSyW+4iOgAsLm9xqQbU/r4D+Q3cg==,iv:8EvxftBoLOGNr5l6ipheFMaKjzxq1sd+68VKDbBtFYw=,tag:G/2rBUkR+prtdSLzvjN2Ww==,type:comment]
#ENC[AES256_GCM,data:HSOYzRiyUIyD3TUsOjtjsFLqhbGSsgZDW3wyOv78ysWAfuQuVK8yYu3GvNAMYW09/LATFGwtf6Q/rnxY0ebh/+s=,iv:XrGPZhQcz36ZUcscKNhFL+aaPWuJbQIAM6nueAi7jB8=,tag:XSOzu1bAPUwMZ6evjdJGmg==,type:comment]
root_password: ENC[AES256_GCM,data:2yljdlPaKDMc1rCmALk=,iv:iae1Pg+DuT3xgZCxv7L+CvnTe2e5bKwYzuT/bgVLAe4=,tag:OAbUSlgeZsMb0MBXX/fiaw==,type:str]
#ENC[AES256_GCM,data:t+1dBYeoZ5ffDsQWCgnm+9jfZYtosS/26JLxmvZCKp8m,iv:kOwH1povIIiGx98SnXdxm05tG82O26epcfkEC8bgEh8=,tag:21mML8I4R5+DqP8kG2pwjA==,type:comment]
#ENC[AES256_GCM,data:UavCssmna31QysfHv9MtzTCQutNfkdB37JaO9HAE3Cb7rrxEfZf+cOvCjsZSPsCdWA==,iv:m7/3y/kZqz7B+KaYbVaqnAca9k62gluHPqwymVos6fM=,tag:K27vKwRjk9C0RXxZQGGPCg==,type:comment]
sops:
    age:
        - recipient: age1mcru7nhu2ct4g30kffqxhy3wxq44vuuawzu4j7frf5qc024uudvq75mpvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQXVUN0s1T2FIUU5qTWxy
            cGFGMjlKTGVvdE13eCtmOUY0UTNDdmxWZlZ3CmE0Y3JiV2ZXMmRDOW1hNDd2c0FQ
            S1NQLzFuelo2N0xKSDc3OUpuaVZVamsKLS0tIDdiQ3lPRGh5K3hWRmRrNEJjeHdh
            Z085ZVhXWUszWkZIQkFUZjdpT3d1TzAK8eqJUKMVmorMoUu/QWVxxbze3LyCjjhF
            yB/2DQWUYuL/bTng5aTU28wmjdxsUJA3Y6HN/rQfxdYTtW6HmhPkLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:40:52Z"
    mac: ENC[AES256_GCM,data:f7VRRfoPp8O3pjqPwflcm3B8AcfHNI2uZ9gq0cU8lNFt/HdsZpKJcm+Q6GJZoSDo3D9AUas5m+Sj3dizaCaL2rSNGuUcqWTNHQ1eRBOER7XCrKZBzcIdlVznYECDiOigBMe42jCR2YNUG/mOaBWti804waMsUf2VOLs+jNQwj/k=,iv:Wlp5rKwI44hzv2ZiCTJAW4cJEQt1kgPyxlKlPb9rUT8=,tag:yBMOYEH53nEOrfQRnu70ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
