creation_rules:
  - path_regex: 'secrets\.(yaml|yml|json|env)$'
    age: "age1mcru7nhu2ct4g30kffqxhy3wxq44vuuawzu4j7frf5qc024uudvq75mpvj"
  - path_regex: '.*\.sops\.(yaml|yml|json)$'
    age: "age1mcru7nhu2ct4g30kffqxhy3wxq44vuuawzu4j7frf5qc024uudvq75mpvj"